### ISSUE TITLE
error when running npm run sandbox:start

### ISSUE THREAD

**Issue by songproducer** [stove-labs/tezos-starter-kit#7] opened 2020-09-10 17:47 UTC
```
docker: Error response from daemon: Conflict. The container name "/flextesa-mini-archive" is already in use by container "e1398f0fa72a802c507eb8c3dcfd06aedcecfc178d7eecc1ea0720c53fc78b9b". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

(node:72500) UnhandledPromiseRejectionWarning: Error: docker: Error response from daemon: Conflict. The container name "/flextesa-mini-archive" is already in use by container "e1398f0fa72a802c507eb8c3dcfd06aedcecfc178d7eecc1ea0720c53fc78b9b". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

    at ChildProcess.onClosed (/Users/leotreasure/tezos-starter-kit/node_modules/ganache-core/lib/tezos/flextesa.js:219:18)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:321:20)
    at Pipe.<anonymous> (net.js:668:12)
(node:72500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:72500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dexterslabor** [comment] 2020-09-11 08:05
Hi and welcome @songproducer 

The problem is that for some reason you already have the docker container running. You need to close it before you can restart the sandbox. I recommend you doing it in two ways:

1) Using the **script**: If you are on a previous version of the starter kit, simply type `npm run sandbox:kill -- carthage`.

2) **Manually**: You can list all running docker containers by typing `docker ps` in your terminal. Then copy the docker_id and type `docker stop docker_id`. You can read a quick guide [here](https://www.thegeekdiary.com/how-to-list-start-stop-delete-docker-containers/#Stopping-a-Docker-Container).

After doing this, I highly recommend you to use the newest version of the starter kit. There is no need to stop docker containers in this way.

**Comment by songproducer** [comment] 2020-09-13 11:14
Thanks! Where is the newer version of the starter kit please?

**Comment by dexterslabor** [comment] 2020-09-14 09:36
I am glad I could help you.

The dev branch is up-to-date and the newest version. If you do `git pull` in the repository it should say: _Already up to date._

**Closed as completed by dexterslabor** 2020-09-14 09:36 UTC
